version: '3'
services:
    redis:
        image: redislabs/redismod
        volumes:
            - redis-data:/data
            - redis-conf:/usr/local/etc/redis/redis.conf
        restart: always
        deploy:
            replicas: 1
    redisinsight:
        image: redislabs/redisinsight:latest
        ports:
            - 8884:8001
        volumes:
            - insight-db:/db
        restart: always
        depends_on:
            - redis
        deploy:
            replicas: 1
    api:
        ports:
            - 8883:80
        image: ${IMAGE_NAME}-api:latest
        deploy:
            replicas: 4
        restart: always
        depends_on:
            - redis
    frontend:
        ports:
            - 8882:3000
        image: ${IMAGE_NAME}-frontend:latest
        deploy:
            replicas: 1
        restart: always
        depends_on:
            - api
    
volumes:
    redis-data:
    redis-conf:
    insight-db: